server:
  port: 6060

spring:
  datasource:
    url: jdbc:h2:file:~/.pingpong/database
    username: "test"
    password: "test"
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: tr
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true